// <auto-generated />
using System;
using Folio.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Folio.API.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260518213410_Init")]
    partial class Init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Folio.API.Models.Analysis", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("CandidateName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("CandidateTitle")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("OverallScore")
                        .HasColumnType("int");

                    b.Property<string>("ResultJson")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("SelectedTemplateId")
                        .HasColumnType("longtext");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Analyses");
                });

            modelBuilder.Entity("Folio.API.Models.Payment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(65,30)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("PaymobOrderId")
                        .HasColumnType("longtext");

                    b.Property<string>("PaymobTransactionId")
                        .HasColumnType("longtext");

                    b.Property<int>("Plan")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Payments");
                });

            modelBuilder.Entity("Folio.API.Models.Subscription", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("AnalysesResetDate")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("AnalysesUsedThisMonth")
                        .HasColumnType("int");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("PaymobOrderId")
                        .HasColumnType("longtext");

                    b.Property<int>("Plan")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Subscriptions");
                });

            modelBuilder.Entity("Folio.API.Models.Template", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsFree")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("PreviewBg")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("PreviewHeader")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("PreviewSkill")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("PreviewTag")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.Property<string>("Style")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("Templates");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 5, 18, 21, 34, 8, 407, DateTimeKind.Utc).AddTicks(6447),
                            Description = "Clean, typographic, and timeless. Perfect for developers who let their work speak.",
                            IsActive = true,
                            IsFree = true,
                            Name = "Lumière",
                            PreviewBg = "#fafaf8",
                            PreviewHeader = "#1c1a16",
                            PreviewSkill = "#d4a843",
                            PreviewTag = "#f5edd8",
                            Slug = "lumiere",
                            SortOrder = 1,
                            Style = "Minimal & Editorial"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2026, 5, 18, 21, 34, 8, 407, DateTimeKind.Utc).AddTicks(6455),
                            Description = "Nature-inspired with strong teal accents. Great for designers and full-stack devs.",
                            IsActive = true,
                            IsFree = true,
                            Name = "Verdant",
                            PreviewBg = "#f0fafa",
                            PreviewHeader = "#2a7c7c",
                            PreviewSkill = "#3da8a8",
                            PreviewTag = "#d4eded",
                            Slug = "verdant",
                            SortOrder = 2,
                            Style = "Creative & Bold"
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2026, 5, 18, 21, 34, 8, 407, DateTimeKind.Utc).AddTicks(6458),
                            Description = "Deep dark backgrounds with electric blue highlights. Makes a strong first impression.",
                            IsActive = true,
                            IsFree = true,
                            Name = "Nova",
                            PreviewBg = "#0d1117",
                            PreviewHeader = "#58a6ff",
                            PreviewSkill = "#388bfd",
                            PreviewTag = "#161b22",
                            Slug = "nova",
                            SortOrder = 3,
                            Style = "Dark & Futuristic"
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2026, 5, 18, 21, 34, 8, 407, DateTimeKind.Utc).AddTicks(6460),
                            Description = "Gold accents on deep dark backgrounds. For seniors who mean business.",
                            IsActive = true,
                            IsFree = false,
                            Name = "Gilded",
                            PreviewBg = "#1a1814",
                            PreviewHeader = "#d4a843",
                            PreviewSkill = "#e8c96b",
                            PreviewTag = "#3a3220",
                            Slug = "gilded",
                            SortOrder = 4,
                            Style = "Luxury & Refined"
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2026, 5, 18, 21, 34, 8, 407, DateTimeKind.Utc).AddTicks(6462),
                            Description = "Violet gradients and soft depth. Stands out in a sea of boring portfolios.",
                            IsActive = true,
                            IsFree = false,
                            Name = "Aurora",
                            PreviewBg = "#f7f5ff",
                            PreviewHeader = "#6b4fa8",
                            PreviewSkill = "#8e72c4",
                            PreviewTag = "#ede8f8",
                            Slug = "aurora",
                            SortOrder = 5,
                            Style = "Vibrant & Modern"
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(2026, 5, 18, 21, 34, 8, 407, DateTimeKind.Utc).AddTicks(6465),
                            Description = "Rose tones and warm whites. Perfect for UX designers and content creators.",
                            IsActive = true,
                            IsFree = false,
                            Name = "Blush",
                            PreviewBg = "#fff8f9",
                            PreviewHeader = "#c24b6e",
                            PreviewSkill = "#e06d8a",
                            PreviewTag = "#fce8ef",
                            Slug = "blush",
                            SortOrder = 6,
                            Style = "Warm & Approachable"
                        },
                        new
                        {
                            Id = 7,
                            CreatedAt = new DateTime(2026, 5, 18, 21, 34, 8, 407, DateTimeKind.Utc).AddTicks(6467),
                            Description = "High contrast, monochrome, no-nonsense. Backend devs will love this.",
                            IsActive = true,
                            IsFree = false,
                            Name = "Slate",
                            PreviewBg = "#f8fafc",
                            PreviewHeader = "#334155",
                            PreviewSkill = "#64748b",
                            PreviewTag = "#e2e8f0",
                            Slug = "slate",
                            SortOrder = 7,
                            Style = "Brutalist & Raw"
                        },
                        new
                        {
                            Id = 8,
                            CreatedAt = new DateTime(2026, 5, 18, 21, 34, 8, 407, DateTimeKind.Utc).AddTicks(6469),
                            Description = "Warm terracotta and olive tones. For creatives who value authenticity over flash.",
                            IsActive = true,
                            IsFree = false,
                            Name = "Terra",
                            PreviewBg = "#fdf6f0",
                            PreviewHeader = "#8b4513",
                            PreviewSkill = "#cd853f",
                            PreviewTag = "#f5e6d3",
                            Slug = "terra",
                            SortOrder = 8,
                            Style = "Earthy & Organic"
                        },
                        new
                        {
                            Id = 9,
                            CreatedAt = new DateTime(2026, 5, 18, 21, 34, 8, 407, DateTimeKind.Utc).AddTicks(6471),
                            Description = "Pure white with icy blue accents. Ultra-clean, Scandinavian-inspired layout.",
                            IsActive = true,
                            IsFree = false,
                            Name = "Arctic",
                            PreviewBg = "#f0f8ff",
                            PreviewHeader = "#1e3a5f",
                            PreviewSkill = "#4a90d9",
                            PreviewTag = "#ddeeff",
                            Slug = "arctic",
                            SortOrder = 9,
                            Style = "Ice-Cold Minimal"
                        },
                        new
                        {
                            Id = 10,
                            CreatedAt = new DateTime(2026, 5, 18, 21, 34, 8, 407, DateTimeKind.Utc).AddTicks(6474),
                            Description = "Full dark mode with deep purple and silver. The most premium-feeling template in the set.",
                            IsActive = true,
                            IsFree = false,
                            Name = "Obsidian",
                            PreviewBg = "#111118",
                            PreviewHeader = "#a78bfa",
                            PreviewSkill = "#7c3aed",
                            PreviewTag = "#1e1b4b",
                            Slug = "obsidian",
                            SortOrder = 10,
                            Style = "Premium Dark Mode"
                        });
                });

            modelBuilder.Entity("Folio.API.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("AvatarUrl")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("GoogleId")
                        .HasColumnType("longtext");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsAdmin")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("longtext");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Folio.API.Models.Analysis", b =>
                {
                    b.HasOne("Folio.API.Models.User", "User")
                        .WithMany("Analyses")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Folio.API.Models.Payment", b =>
                {
                    b.HasOne("Folio.API.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Folio.API.Models.Subscription", b =>
                {
                    b.HasOne("Folio.API.Models.User", "User")
                        .WithOne("Subscription")
                        .HasForeignKey("Folio.API.Models.Subscription", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Folio.API.Models.User", b =>
                {
                    b.Navigation("Analyses");

                    b.Navigation("Subscription");
                });
#pragma warning restore 612, 618
        }
    }
}
